# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_plugin 'vagrant-lxc'

Vagrant.configure("2") do |config|
  config.vm.box      = "ubuntu-cloud"
  config.vm.hostname = 'ubuntu-cloud-box'

  config.vm.provider :lxc do |lxc|
    # ... soon to come lxc configs...
  end
end
