unless ENV['USER'] == 'vagrant'
  puts 'This Gemfile is meant to be used from the dev box'
  exit 1
end

source "https://rubygems.org"

gem 'vagrant',     path: '../vagrant'
gem 'vagrant-lxc', path: '../'
