# -*- mode: ruby -*-
# vi: set ft=ruby :

require '../lib/vagrant-lxc'

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-cloud"
  config.vm.provider :lxc do |lxc|
    # ... soon to come lxc configs...
  end
end
