# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_plugin 'vagrant-lxc'
Vagrant.require_plugin 'vagrant-cachier'

Vagrant.configure("2") do |config|
  config.vm.box      = ENV.fetch('BOX_NAME', 'quantal64')
  config.vm.hostname = 'lxc-test-box'

  config.cache.enable :apt

  config.vm.provision :shell,
    inline: 'mkdir -p /vagrant/tmp && echo -n "Provisioned" > /vagrant/tmp/provisioning'

  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.provision :shell,
    inline: 'sudo apt-get install nginx -y && sudo service nginx start'
end
