#!/bin/bash

set -e

if `which puppet > /dev/null`; then
  exit 0
fi

echo 'An old kernel was found on the guest machine and it will be upgraded' 1>&2
echo 'Please reload the box after provisioning when finished' 1>&2

sudo apt-get update
sudo apt-get install puppet -y
