#!/bin/bash

rootfs=$1

echo "installing babushka"
cat > $rootfs/tmp/install-babushka.sh << EOF
#!/bin/sh
curl https://babushka.me/up | sudo bash

EOF
chmod +x $rootfs/tmp/install-babushka.sh
chroot $rootfs /tmp/install-babushka.sh

rm -rf $rootfs/tmp/*
